### ISSUE TITLE
ANSI getting eaten

### ISSUE THREAD

**Issue by tkrajcar** [tkrajcar/pennjson#1]
Somewhere along the way, ANSI escapes are getting eaten.

Replication:

`gem install colored`

Edit ping.rb and add:

```
require 'colored'
  def pj_ansitest
    "Colortime!".red
  end
```

**Comment by kymoon** [comment]
PennMUSH apparently has a fancy new markup system that replaced raw ANSI codes. You get to insert the new PennMUSH-style codes yourself. See src/markup.c.

This is a user systems issue, so I am closing this as something that needs to be fixed at the Ruby level.

**Comment by tkrajcar** [comment]
Fixed in systems with new penncolor.rb.
